
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AppProviders from "./appProvider";
import { Toaster } from "react-hot-toast";
import { useEffect } from "react";
import { getUserContext } from "./app_packages/tocken";
import { useRouter } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hisabuk Route Sale",
  description: "Generated by Datastone Solutions",
  manifest: "/manifest.json",
  themeColor: "#1e3a8a",
  viewport:
    "width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppProviders>{children}</AppProviders>
        <Toaster />
      </body>
    </html>
  );
}
